pub enum TokenType {
    Iden(String),
    LiteralIntDec(i32),
    LiteralIntBin(i32),
    LiteralIntOct(i32),
    LiteralIntHex(i32),
    LiteralChar(char),
    LiteralFloat(f32),
    LiteralStr(String),
    Lpar,
    Rpar,
    Lbracket,
    Rbracket,
    Lbrace,
    Rbrace,
    Lt,
    Gt,
    Leq,
    Geq,
    Eq,
    Neq,
    Assign,
    Plus,
    Minus,
    Asterisk,
    Slash,
    Percent,
    Pipe,
    Amp,
    Tilde,
    Semicolon,
    Colon,
    Coma,
    Period,
    Lc(String),
    Bc(String),
    KwFor,
    KwTo,
    KwWhile,
    KwIf,
    KwElse,
    KwTrue,
    KwFalse,
    KwOr,
    KwAnd,
    KwNot,
    KwLet,
    KwFn,
    KwInt,
    KwChar,
    KwBool,
    KwFloat,
    KwStr,
}

impl std::fmt::Display for TokenType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TokenType::Iden(id) => f.write_str(id),
            TokenType::LiteralIntDec(n) => write!(f, "{n}"),
            TokenType::LiteralIntBin(n) => write!(f, "{n}"),
            TokenType::LiteralIntOct(n) => write!(f, "{n}"),
            TokenType::LiteralIntHex(n) => write!(f, "{n}"),
            TokenType::LiteralChar(c) => write!(f, "{c}"),
            TokenType::LiteralFloat(num) => write!(f, "{num}"),
            TokenType::LiteralStr(s) => f.write_str(s),
            TokenType::Lpar => f.write_str("("),
            TokenType::Rpar => f.write_str(")"),
            TokenType::Lbracket => f.write_str("["),
            TokenType::Rbracket => f.write_str("]"),
            TokenType::Lbrace => f.write_str("{"),
            TokenType::Rbrace => f.write_str("}"),
            TokenType::Lt => f.write_str("<"),
            TokenType::Gt => f.write_str(">"),
            TokenType::Leq => f.write_str("<="),
            TokenType::Geq => f.write_str(">="),
            TokenType::Eq => f.write_str("=="),
            TokenType::Neq => f.write_str("!="),
            TokenType::Assign => f.write_str("="),
            TokenType::Plus => f.write_str("+"),
            TokenType::Minus => f.write_str("-"),
            TokenType::Asterisk => f.write_str("*"),
            TokenType::Slash => f.write_str("/"),
            TokenType::Percent => f.write_str("%"),
            TokenType::Pipe => f.write_str("|"),
            TokenType::Amp => f.write_str("&"),
            TokenType::Tilde => f.write_str("~"),
            TokenType::Semicolon => f.write_str(";"),
            TokenType::Colon => f.write_str(":"),
            TokenType::Coma => f.write_str(","),
            TokenType::Period => f.write_str("."),
            TokenType::Lc(s) => f.write_str(s),
            TokenType::Bc(s) => f.write_str(s),
            TokenType::KwFor => f.write_str("for"),
            TokenType::KwTo => f.write_str("to"),
            TokenType::KwWhile => f.write_str("while"),
            TokenType::KwIf => f.write_str("if"),
            TokenType::KwElse => f.write_str("else"),
            TokenType::KwTrue => f.write_str("true"),
            TokenType::KwFalse => f.write_str("false"),
            TokenType::KwOr => f.write_str("or"),
            TokenType::KwAnd => f.write_str("and"),
            TokenType::KwNot => f.write_str("not"),
            TokenType::KwLet => f.write_str("let"),
            TokenType::KwFn => f.write_str("fn"),
            TokenType::KwInt => f.write_str("int"),
            TokenType::KwChar => f.write_str("char"),
            TokenType::KwBool => f.write_str("bool"),
            TokenType::KwFloat => f.write_str("float"),
            TokenType::KwStr => f.write_str("str"),
        }
    }
}
